apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sample-api
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: sample-api
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: /dev/sample-api
        property: API_KEY
