apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrelease.yaml
  - clusterissuers/letsencrypt-staging.yaml
  - clusterissuers/letsencrypt-prod.yaml
