apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sa.yaml
  - helmrelease.yaml
  - provisioners/default-nodeclass.yaml
  - provisioners/default-provisioner.yaml
