apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sa.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: alb-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
